### ISSUE TITLE
Client chat not working / visible

### ISSUE THREAD

**Issue by lbg-utils** [mmtrt/leagueoflegends#108]
First, thanks for the great work!

The following issue arises after starting and logging in:  
* The whole friend list is missing, I cannot see any online or offline players.
* When I open a lobby and get to champ select (in a custom game) and leave the champ selection, the friend list shows up, but I cannot write a message as the message window does not appear.

In particular, the whole right column is just dark.

The mission window, however, does appear.

![image](https://user-images.githubusercontent.com/60315467/73134810-51edab80-403b-11ea-8167-b0fe2316e7cf.png)

**Comment by mmtrt** [comment]
Known issue recently users have with launcher https://www.reddit.com/r/leagueoflinux/comments/esz0z1/arch_league_not_starting_on_lutris/

it's usually hit and miss sometimes works some time broken try user suggustions from link see if that helps.

**Comment by ondrakubicek** [comment]
![chat_connecting](https://user-images.githubusercontent.com/17781638/73142408-8474c400-408e-11ea-8ba2-c475eb5dcf01.png)
i am having simmilar issue. At joining lobby the chat is connection too long but its does after a while. But then i cannot se history so others think i am *** trying to call their line.. pretty annoying

**Comment by Amoki** [comment]
Someone said it's fixed in dxvk 1.5.1 (https://www.reddit.com/r/leagueoflinux/comments/esit6l/arch_no_chatsidebar/ffsghaq)
How can we try it?

**Comment by lbg-utils** [comment]
I cannot confirm this. I already tried DXVK 1.5.2 (and also 1.5.1), but the issue still appears.

**Comment by Getta91** [comment]
I had the same problem on lutris. Its because of the audio driver.. By default it is alsa used and u need pulseaudio or maybe is it the reverse? I don't remember well but its about those audio drivers.

**Comment by Getta91** [comment]
MB, just did a full repair and no problem either

**Comment by lbg-utils** [comment]
Using Lutris with Wine 5 (lol-version) fixed it for me

**Comment by Ignacy-s** [comment]
> MB, just did a full repair and no problem either

Does it consistently work after  switching to alsa or after the full repair?

**Comment by Ignacy-s** [comment]
> Using Lutris with Wine 5 (lol-version) fixed it for me

Can you link the installation script? I can see a couple different versions on Lutris League of Legends page. https://lutris.net/games/league-of-legends/

**Comment by lbg-utils** [comment]
I used the first one in the list, labeled as "Gold".  
Nonetheless, as stated in the description, Rito will break usage with Wine permanently next year...  
After installation, install lutris-lol-5.0-x86_64 as the wine runner and select it in the "configure" menu in "Runner options" tab.  
I also set DXVK to 1.5.3 in the same menu.

Since using wine 5, I can use the chat as intended and have no problems with using League at all.

**Comment by Ignacy-s** [comment]
Thank you for taking the time to reply and describe the process. I'll give
it a shot.


On Tue, Feb 11, 2020, 14:06 lbg-utils  <>
wrote:

>
> I used the first one in the list, labeled as "Gold".
> Nonetheless, as stated in the description, Rito will break usage with Wine
> permanently next year...
>
I'm just as disappointed 😞

**Comment by Amoki** [comment]
I did nothing and it came back after a client update :thinking:

**Comment by Bloodiko** [comment]
For me this issue Persists too - i've even wrote the support about it
First reaction was that my game may not be in the normal /Riot Games/League of Legends/ Path - 
It is though , - waiting for another answer now - not sure if it is an League issue or an Wine/Linux issue - because all windows counterparts i know who seemed to have this issue did get resolved like 2 games after encountering , or when reloading the client
...

Still hoping for a fix , though MMTRT may not be able to fix this one

**Comment by Gubby1** [comment]
> ![chat_connecting](https://user-images.githubusercontent.com/17781638/73142408-8474c400-408e-11ea-8ba2-c475eb5dcf01.png) i am having simmilar issue. At joining lobby the chat is connection too long but its does after a while. But then i cannot se history so others think i am *** trying to call their line.. pretty annoying

How did you fix that?
