### ISSUE TITLE
Please add Vietnam region. Thanks! <3

### ISSUE THREAD

**Issue by nd-thang** [mmtrt/leagueoflegends#216]
From Jan 6th 2023, players from region Vietnam start using riot account and riot client for playing lol instead of garena client. Please add VN region. Thanks <3

**Comment by mmtrt** [comment]
Should be added now.

**Comment by nd-thang** [comment]
I have updated the latest but i do not see the VN region to choose to install though i have seen your new function install_vn() in /snap/leagueoflegends/current/bin/sommelier. What should i do?

**Comment by mmtrt** [comment]
Script had typos it should work now.

**Comment by nd-thang** [comment]
VN entry still not be displayed in install menu. Can you check it again?

**Comment by mmtrt** [comment]
should be ok now tested, it is showing VN now.
